

# see: http://memorynotfound.com/spring-boot-spring-data-jpa-hibernate-h2-web-console/

server:
  port: 8080

spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:~/test;AUTO_SERVER=TRUE
    username: sa
    password: sa
  jpa:
    database: H2
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties.hibernate.dialect: org.hibernate.dialect.H2Dialect


  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: true


# database setup config
liquibase:
  change-log: classpath:/db/changelog/db.changelog-master.xml


# JWT Auth
auth:
  secret: some-random-secret
  expires: 604800
  header: Authorization

security:
  basic:
    enabled: false


