

# see: http://memorynotfound.com/spring-boot-spring-data-jpa-hibernate-h2-web-console/

server:
  port: 8080

spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:~/test;AUTO_SERVER=TRUE
    username: sa
    password: sa
  jpa:
    database: H2
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties.hibernate.dialect: org.hibernate.dialect.H2Dialect


  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: true


# database setup config
liquibase:
  change-log: classpath:/db/changelog/db.changelog-master.xml


# JWT Auth
auth:
  secret: some-random-secret
  expires: 604800
  header: Authorization

security:
  basic:
    enabled: false

facebook: # see: https://developers.facebook.com/apps
  client:
    clientId: 1368363149952141
    clientSecret: 688aef685b7ac53a44f11cf73879f124
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    accessTokenUri: https://graph.facebook.com/oauth/access_token/
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
    preEstablishedRedirectUri: http://localhost:8080/login/facebook
  resource:
    userInfoUri: https://graph.facebook.com/me

github: # see: https://developers.facebook.com/apps
  client:
    clientId: 1480763144c36b2301b6
    clientSecret: 3cff933b9748f783a9a4402b51b60ca8e482b3ff
    userAuthorizationUri: https://github.com/login/oauth/authorize
    scope: user
    accessTokenUri: https://github.com/login/oauth/access_token/
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
    preEstablishedRedirectUri: http://localhost:8080/login/github
  resource:
    userInfoUri: https://graph.facebook.com/me

logging:
    level:
        org.springframework: DEBUG