

# see: http://memorynotfound.com/spring-boot-spring-data-jpa-hibernate-h2-web-console/

server:
  port: 8080

spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:~/test;AUTO_SERVER=TRUE
    username: sa
    password: sa
  jpa:
    database: H2
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties.hibernate.dialect: org.hibernate.dialect.H2Dialect


  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: true


# database setup config
liquibase:
  change-log: classpath:/db/changelog/db.changelog-master.xml


# JWT Auth
auth:
  secret: some-random-secret
  expires: 604800
  header: Authorization

security:
  basic:
    enabled: false
  oauth2:
    client:
      preEstablishedRedirectUri: test


facebook: # see: https://developers.facebook.com/apps
  client:
    clientId: 1368363149952141
    clientSecret: 688aef685b7ac53a44f11cf73879f124
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
    preEstablishedRedirectUri: login
    pre-established-redirect-uri: custom
    use-current-uri: false
    useCurrentUri: false
  resource:
    userInfoUri: https://graph.facebook.com/me
    preEstablishedRedirectUri: login
    pre-established-redirect-uri: custom
    use-current-uri: false
    useCurrentUri: false