
server:
  port: 8080

spring.jpa:
    database: HSQL
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties.hibernate.dialect: org.hibernate.dialect.H2Dialect

spring.datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:bootexample


# database setup config
liquibase:
  change-log: classpath:/db/changelog/db.changelog-master.sql


# JWT Auth
auth:
  secret: some-random-secret
  expires: 604800
  header: Authorization

security:
  basic:
    enabled: false


